# Generated by Django 3.0.9 on 2020-08-06 15:54

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PointOfInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datatourism_id', models.CharField(default='', max_length=200)),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='localication')),
                ('street_address', models.CharField(max_length=100, verbose_name='adresse')),
                ('city', models.CharField(max_length=50, verbose_name='commune')),
            ],
            options={
                'verbose_name': "point d'interêt",
                'verbose_name_plural': "points d'interêt",
                'ordering': ('name',),
            },
        ),
    ]
