# Generated by Django 3.0.9 on 2020-08-07 13:33

from django.db import migrations, models
import django.db.models.deletion
import tourism.models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0005_auto_20200807_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('tag', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'categorie',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='category',
            field=models.ForeignKey(default=tourism.models.get_default_category, on_delete=django.db.models.deletion.PROTECT, to='tourism.Category'),
        ),
    ]
