# Generated by Django 3.0.9 on 2020-08-12 10:06

from django.db import migrations, models
import django.db.models.deletion
import tourism.models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0007_data_20200807_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainRepresentation',
            fields=[
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='légende')),
                ('credits', models.CharField(blank=True, max_length=100, null=True, verbose_name='crédits')),
                ('picture', models.ImageField(upload_to=tourism.models.poi_directory_path, verbose_name='image principale')),
                ('poi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tourism.PointOfInterest')),
            ],
            options={
                'verbose_name': 'image principale',
                'verbose_name_plural': 'images principales',
            },
        ),
        migrations.AlterField(
            model_name='pointofinterest',
            name='email',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pointofinterest',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='pointofinterest',
            name='street_address',
            field=models.CharField(blank=True, max_length=100, verbose_name='adresse'),
        ),
        migrations.AlterField(
            model_name='pointofinterest',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
