# Generated by Django 3.0.9 on 2020-08-10 15:20

import datetime
from django.db import migrations, models
import django.db.models.deletion
import tourism.models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0007_data_20200807_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointofinterest',
            name='email',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pointofinterest',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='pointofinterest',
            name='street_address',
            field=models.CharField(blank=True, max_length=100, verbose_name='adresse'),
        ),
        migrations.AlterField(
            model_name='pointofinterest',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='OpeningHoursSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField(default=datetime.date.today, verbose_name='valable à partir du')),
                ('valid_through', models.DateField(blank=True, default=tourism.models.get_valid_through_default, verbose_name="valable jusqu'au")),
                ('poi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourism.PointOfInterest')),
            ],
            options={
                'verbose_name': "période d'ouverture",
                'verbose_name_plural': "périodes d'ouverture",
            },
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(1, 'Lundi'), (2, 'Mardi'), (3, 'Mercredi'), (4, 'Jeudi'), (5, 'Vendredi'), (6, 'Samedi'), (7, 'Dimanche')], verbose_name='jour de la semaine')),
                ('from_hour', models.TimeField(verbose_name="heure d'ouverture")),
                ('to_hour', models.TimeField(verbose_name='heure de fermeture')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourism.OpeningHoursSchema')),
            ],
            options={
                'verbose_name': "horaires d'ouverture",
                'verbose_name_plural': "horaires d'ouverture",
            },
        ),
    ]
