# Generated by Django 3.0.9 on 2020-08-12 10:32

import datetime
from django.db import migrations, models
import django.db.models.deletion
import tourism.models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0009_data_main_img_20200812_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningHoursSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField(default=datetime.date.today, verbose_name='valable à partir du')),
                ('valid_through', models.DateField(blank=True, default=tourism.models.get_valid_through_default, verbose_name="valable jusqu'au")),
                ('poi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourism.PointOfInterest')),
            ],
            options={
                'verbose_name': "période d'ouverture",
                'verbose_name_plural': "périodes d'ouverture",
                'ordering': ['valid_from', 'valid_through'],
            },
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(1, 'Lundi'), (2, 'Mardi'), (3, 'Mercredi'), (4, 'Jeudi'), (5, 'Vendredi'), (6, 'Samedi'), (7, 'Dimanche')], verbose_name='jour de la semaine')),
                ('from_hour', models.TimeField(null=True, verbose_name="heure d'ouverture")),
                ('to_hour', models.TimeField(null=True, verbose_name='heure de fermeture')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourism.OpeningHoursSchema')),
            ],
            options={
                'verbose_name': "horaires d'ouverture",
                'verbose_name_plural': "horaires d'ouverture",
                'ordering': ['weekday', 'from_hour'],
            },
        ),
    ]
