# Generated by Django 3.0.9 on 2020-08-12 14:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0011_data_openingschema_20200812_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nom')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326, verbose_name='géométrie')),
                ('insee', models.CharField(max_length=5, unique=True)),
                ('postal_code', models.CharField(max_length=5)),
                ('in_argonne_pnr', models.BooleanField(verbose_name='fait partie du PNR ?')),
            ],
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='commune',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
