# Generated by Django 3.0.9 on 2020-08-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0014_auto_20200812_1612'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commune',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=10, verbose_name='ordre'),
            preserve_default=False,
        ),
    ]
