# Generated by Django 2.2.14 on 2020-08-19 06:06

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0015_auto_20200814_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('pointofinterest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tourism.PointOfInterest')),
                ('path', django.contrib.gis.db.models.fields.MultiLineStringField(null=True, srid=4326, verbose_name='chemin')),
            ],
            bases=('tourism.pointofinterest',),
        ),
    ]
