# Generated by Django 2.2.14 on 2020-08-28 16:31

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0016_tour'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={'verbose_name': 'randonnée', 'verbose_name_plural': 'randonnées'},
        ),
        migrations.AddField(
            model_name='tour',
            name='distance',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='distance'),
        ),
        migrations.AddField(
            model_name='tour',
            name='downhill',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='dénivelé négatif'),
        ),
        migrations.AddField(
            model_name='tour',
            name='elevation_max',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='altitude minimale'),
        ),
        migrations.AddField(
            model_name='tour',
            name='elevation_min',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='altitude maximale'),
        ),
        migrations.AddField(
            model_name='tour',
            name='is_closed',
            field=models.BooleanField(default=True, verbose_name='est une boucle'),
        ),
        migrations.AddField(
            model_name='tour',
            name='time',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='durée'),
        ),
        migrations.AddField(
            model_name='tour',
            name='uphill',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='dénivelé positif'),
        ),
        migrations.AlterField(
            model_name='pointofinterest',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='path',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(null=True, srid=4326, verbose_name='parcours'),
        ),
    ]
