# Generated by Django 3.0.9 on 2020-09-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0018_pointofinterest_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(max_length=50, verbose_name='icon', default='default'),
            preserve_default=True,
        ),
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
        migrations.AddField(
            model_name='category',
            name='dark_color',
            field=models.CharField(default='#a1334b', max_length=7),
        ),
        migrations.AddField(
            model_name='category',
            name='light_color',
            field=models.CharField(default='#d54363', max_length=7),
        ),
    ]
