# Generated by Django 3.0.9 on 2020-09-18 17:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0019_category_icon_20200903_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointofinterest',
            name='note_of_interest',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
