# Generated by Django 3.0.9 on 2020-09-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0020_pointofinterest_note_of_interest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OpeningHoursSchema',
            new_name='OpeningPeriod',
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='is_always_open',
            field=models.BooleanField(default=False, verbose_name='est en permanence ouvert'),
        ),
    ]
