# Generated by Django 3.0.9 on 2020-09-25 07:28

from django.db import migrations, models
import django.db.models.deletion
import tourism.models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0022_variable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='name',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('icon', models.FileField(upload_to=tourism.models.icon_directory_path, verbose_name='icône')),
                ('order', models.PositiveIntegerField(verbose_name='ordre')),
                ('category', models.ForeignKey(default=tourism.models.get_default_category, on_delete=django.db.models.deletion.PROTECT, to='tourism.Category')),
            ],
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tourism.SubCategory'),
        ),
    ]
