# Generated by Django 3.0.9 on 2020-10-01 17:38

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0025_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneOfInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', django.contrib.gis.db.models.fields.MultiPointField(srid=4326, verbose_name='zone')),
            ],
        ),
        migrations.RemoveField(
            model_name='openingperiod',
            name='poi',
        ),
        migrations.AddField(
            model_name='openingperiod',
            name='place',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tourism.Place'),
            preserve_default=False,
        ),
    ]
