# Generated by Django 3.0.9 on 2020-10-03 08:14

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0026_opening_period_and_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zoneofinterest',
            name='id',
        ),
        migrations.AddField(
            model_name='place',
            name='description_poi',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='zoneofinterest',
            name='place_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tourism.Place'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=100, verbose_name='ordre'),
        ),
        migrations.AlterField(
            model_name='zoneofinterest',
            name='zone',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='zone'),
        ),
    ]
