# Generated by Django 3.0.9 on 2020-10-03 08:16

from django.db import migrations

# def transfer_description_from_poi_to_place(apps, schema_editor):
#     Place = apps.get_model('tourism', 'Place')
#     PointOfInterest = apps.get_model('tourism', 'PointOfInterest')
#     for poi in PointOfInterest.objects.all():
#         poi.description_poi = poi.description
#         poi.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0027_fix_zone_and_place'),
    ]

    operations = [
        # migrations.RunPython(transfer_description_from_poi_to_place),
        migrations.RenameField(
            model_name='place',
            old_name='description_poi',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='pointofinterest',
            name='description',
        ),
    ]
