# Generated by Django 3.0.9 on 2020-10-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0028_auto_20201003_1016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zoneofinterest',
            options={'ordering': ('name',), 'verbose_name': "zone d'interêt", 'verbose_name_plural': "zones d'interêt"},
        ),
        migrations.AddField(
            model_name='place',
            name='published',
            field=models.BooleanField(default=True, verbose_name='est publié'),
        ),
    ]
